config/routes.rb
Rails.application.routes.draw do
  get "/", to: "flats#index"
  get "flats/:id", to: "flats#show", as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  FLATS_URL = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"

  def index
    @flats = JSON.parse(URI.open(FLATS_URL).read)
  end

  def show
    @flats = JSON.parse(URI.open(FLATS_URL).read)
    @flat = @flats.select { |flat| flat["id"] == params["id"].to_i }.first
    # flat_array = @flats.select do |flat|
    #   flat["id"] == params["id"].to_i
    # end
    # @flat = flat_array.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>

<ul>
  <% @flats.each do |flat| %>
    <li>
      <%= link_to flat["name"], flat_path(flat["id"]) %>
      <%= flat["price"] %> <%= flat["priceCurrency"] %>
    </li>
  <% end %>
</ul>

app/views/flats/show.html.erb
<h1> <%= @flat["name"] %> </h1>
<h3> <%= @flat["price"] %> <%= @flat["priceCurrency"] %> </h3>
<%= image_tag @flat["imageUrl"] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StaticAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>